//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class signup
    {
        public string uId { get; set; }
        public string uName { get; set; }
        public string uPwd { get; set; }
        public string uEmail { get; set; }
        public string phnNo { get; set; }
    }
}
