//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class signup
    {
        [Key]
        [DisplayName("UserId")]
        public string uId { get; set; }
        [DisplayName("Username")]
        [Required(ErrorMessage ="enter user name")]
        public string uName { get; set; }
        [DisplayName("Password")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "Minimum 6 characters required")]
        public string uPwd { get; set; }
        [DisplayName("Email")]
        public string uEmail { get; set; }
        [DisplayName("Phn Number")]
        public string phnNo { get; set; }
    }
}
