//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookService
    {
        public int custId { get; set; }
        public string custName { get; set; }
        public string vehicleNo { get; set; }
        public Nullable<System.DateTime> bookingDate { get; set; }
        public string contactNumber { get; set; }
        public string bookStutus { get; set; }
    }
}
