//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BookService
    {
        [Key]
        public int custId { get; set; }
        [Required]
        public string custName { get; set; }
        [Required]
        public string vehicleNo { get; set; }
        [Required]
        public Nullable<System.DateTime> bookingDate { get; set; }
        [Required]
        public string contactNumber { get; set; }

        public string bookStutus { get; set; }
    }
}
