//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudyonSms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cours
    {
        [Key]
        public int courseId { get; set; }
        [Display(Name = "Student Name")]
        public Nullable<int> stuId { get; set; }
        [Required(ErrorMessage = "Course Name is required")]
        [Display(Name = "Course Name")]
        public string courseName { get; set; }
        [Required(ErrorMessage = "Duration is required")]
        [Display(Name = "Course Duration")]
        public string courseDuration { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
