//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandsOnDatabaseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class stuinfo
    {
        public string stuId { get; set; }
        public string stuName { get; set; }
        public string phnNo { get; set; }
    }
}
